

/control/verbose 2
/run/verbose 2

#################################
/vis/open VRML2FILE
/vis/drawVolume
#/vis/viewer/flush

/vis/scene/add/axes 0 0 0 0.1 m
/vis/scene/add/hits

/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate

/vis/viewer/set/autoRefresh true
/vis/verbose warnings
##################################


/globalField/setValue 0 0 0 tesla

/tracking/verbose 1
/event/verbose 0

#particle
/gun/particle gamma
/gun/energy 6 MeV


/run/beamOn 500
